# defaults
defaults:
  - model: Baseline
  - dataset: CRAFT
  - optimizer: Adam
  - hydra/job_logging: disabled

# experiment
seed: 1
image_size: 112
resume: true
trainer:
  gpus: 1
  max_epochs: 75
  gradient_clip_val: 1.0
  val_check_interval: 1.00
  resume_from_checkpoint: null
  precision: 16

# data loader
loader:
  batch_size: 64
  pin_memory: false
  num_workers: 5

# logger (tensorboard)
logger:
  name: null
  version: null
  save_dir: ~/logs/intphys/emnlp

# checkpoint
checkpoint:
  save_top_k: 1
  save_last: true
  verbose: true
  monitor: "val_accuracy"
  mode: "max"

# resume training
checkpoint_path: null

hydra:
  run:
    dir: .
